### PR TITLE
Forum back

### LINKED ISSUE #5: [FEATURE] Forum Design and Backend
A User is Logged in. 
He can go to the forum page.
He can view all the topics and sub topics
He can start a new thread under a topic(category) by clicking on the new thread button.
He can comment on other threads

A user is not logged in
He can view the topics

### PR DESCRIPTION
**Pull request by Stephen-Kamau**
## Description
....I have create models for chat , forum and thread
....I have also registered them to admin

## How Has This Been Tested?
...running it in my local machine

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by dabusharsystems — DISMISSED** [review]
I think we can force merge becaue your errors are mostly styling issues.

**Review by dengsang — DISMISSED** [review]
I think this is okay. Some of the codacy issues basically need to be ignored, We need to find a way of ignoring them because style issues seems to be recurring.

**Review by dabusharsystems — DISMISSED** [review]
I see your codacy checks are passing somewhat. Its amber though.

**Review by jimmyaduvagah — APPROVED** [review]
ok

**Review by dabusharsystems — APPROVED** [review]
Awesome Stuff

**Review by dengsang — APPROVED** [review]
Well done Stephen

**Pull request merged**
